# Generated by Django 3.2.4 on 2021-06-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoListIten',
            new_name='ToDoListItem',
        ),
    ]
